spring.profiles.active=dev

spring.application.name=HostelManagementSyst
#razorpay.key-id=YOUR_REAL_RAZORPAY_KEY_ID
#razorpay.key-secret=YOUR_REAL_RAZORPAY_KEY_SECRET


#Razor pay for testing
razorpay.key-id=rzp_test_92Bsa6uS6B6B5t
razorpay.key-secret=dummy_secret_not_needed

# A maximum file size of 10 MB will be allowed for a single file.
spring.servlet.multipart.max-file-size=10MB

# The total size of the entire request (file + other text parameters) will be allowed up to 10 MB.
spring.servlet.multipart.max-request-size=10MB
